### ISSUE TITLE
vsFilterscript breaks this again...

### ISSUE THREAD

**Issue by brucethemoose** [IFeelBloated/vapoursynth-mvtools-sf#22]
Like the last issue, but this time its:

`In file included from /usr/include/vsFilterScript/Plugin.vxx:2,
                 from /usr/include/vsFilterScript/Core.vxx:2,
                 from /usr/include/vsFilterScript/Interface.vxx:2,
                 from ../mvtools_sf/src/EntryPoint.cxx:1:
/usr/include/vsFilterScript/Map.vxx:2:10: fatal error: VideoNode.vxx: No such file or directory
    2 | #include "VideoNode.vxx"
      |          ^~~~~~~~~~~~~~~
compilation terminated.
ninja: build stopped: subcommand failed.
==> ERROR: A failure occurred in build().
    Aborting...`

**Comment by 4re** [comment]
Trying to figure out why it's not working for you. What versions of the package and deps are you using (distro, exact package, etc)?

**Comment by IFeelBloated** [comment]
this file does not exist in the stable branch, are you building from the master branch?

**Comment by brucethemoose** [comment]
Sorry for not being specific. I was... grumpy. I'm building on Arch Linux from this AUR package. 

https://aur.archlinux.org/packages/vapoursynth-plugin-mvtools_sf-git/

Which depends on this:

https://aur.archlinux.org/packages/vapoursynth-lib-vsfilterscript-git/

Problem is, the vsfilterscript aur package pulls from the unstable branch, not the stable one. So I edited the package info and built from the stable branch instead, which seemed to work. 

I suppose AUR is still trying to get the unstable branch then...

**Comment by 4re** [comment]
If I understood it correctly you already fixed by editing the arch packages but instead send a bug report here, you should send a patch there to fix the issue.

**Comment by sl1pkn07** [comment]
done in AUR. try now

**Comment by brucethemoose** [comment]
I'm new to Arch. I intended to submit an change, but kinda ran out of time the last few days.

Thanks for the fix, and for the quick response!
