### ISSUE TITLE
fail build

### ISSUE THREAD

**Issue by sl1pkn07** [IFeelBloated/vapoursynth-mvtools-sf#3]
https://sl1pkn07.wtf/paste/view/11cbeee3

gcc 6.1.1

**Comment by IFeelBloated** [comment]
okay, I will try to fix it when I got some time...

**Comment by IFeelBloated** [comment]
Holy Jesus fvcking Christ, that log reported like piles of errors...
How come vs2015 gave me no error, not even a warning..

**Comment by IFeelBloated** [comment]
@4re just updated compiling files, is it working now?

**Comment by sl1pkn07** [comment]
nope

https://sl1pkn07.wtf/paste/view/20eb7eeb
