### ISSUE TITLE
Undefinded symbol when run wobbly with mvtools-sf installed

### ISSUE THREAD

**Issue by sl1pkn07** [IFeelBloated/vapoursynth-mvtools-sf#6]
Hi

sinply when run wobbly:

```
wobbly: symbol lookup error: /usr/lib/vapoursynth/libmvtoolssf.so: undefined symbol: _Z14mvflowRegisterPFvPKcS0_PFvPK5VSMapPS1_PvP6VSCorePK5VSAPIES5_P8VSPluginESE_
```

wobby and mvtools-sf from git

**Comment by 4re** [comment]
That undefined symbol translates to: `mvflowRegister(void (*)(char const*, char const*, void (*)(VSMap const*, VSMap*, void*, VSCore*, VSAPI const*), void*, VSPlugin*), VSPlugin*)`

**Comment by IFeelBloated** [comment]
good now?

**Comment by sl1pkn07** [comment]
yep. the undefined symbol is gone

zankius
