### ISSUE TITLE
Cannot load plugin. "A DLL dependency is probably missing"

### ISSUE THREAD

**Issue by kageru** [IFeelBloated/vapoursynth-mvtools-sf#8]
I cannot load the plugin into vapoursynth. Having the .dll in my vapoursynth/plugins64 will result in a silent fail, and using std.LoadPlugin() produces the following error:
`Error: Failed to load C:\Program Files (x86)\VapourSynth\plugins64\libmvtools_sf_em64t.dll. GetLastError() returned 126. A DLL dependency is probably missing.`
This error occurs on two different computers, both running windows 10 64bit and vapoursynth R37.
I tried older versions of the plugin, but the error message did not change.

**Comment by 4re** [comment]
http://www.fftw.org/install/windows.html

**Comment by kageru** [comment]
That fixed it. Thank you very much.
Is this dependency listed anywhere? If not, you could add it to the readme to prevent future issues like this one.
